name: cbj_remote_pipes
description: A simple command-line application.
version: 1.0.0
homepage: https://cybearjinni.com

environment:
  sdk: ^2.17.1

dependencies:
  # Utility classes to work with asynchronous computations.
  async: ^2.9.0
  # High performance, open-source universal RPC framework.
  grpc: ^3.0.2
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^1.1.0
  # Runtime library for protocol buffers support.
  protobuf: ^2.1.0
  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^3.0.6

dev_dependencies:
  # Collection of lint rules for Dart and Flutter projects
  lint: ^1.8.2
