name: cbj_remote_pipes
description: A simple command-line application.
version: 1.0.0
homepage: https://cybearjinni.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  async: ^2.7.0
  grpc: ^3.0.0
  # Collection of lint rules for Dart and Flutter projects
  lint: ^1.5.3
  protobuf: ^2.0.0
  uuid: ^3.0.4

dev_dependencies:
  pedantic: ^1.11.1
